### ISSUE TITLE
checking non-arguments

### ISSUE THREAD

**Issue by timoxley** [kentcdodds/api-check#14]
API is pretty clunky if you want to use api-check outside validation of arguments, where everything seems to need to be wrapped in an array.

``` js
var apiCheck = require('api-check')()
apiCheck.throw([apiCheck.string], ['abc'])
```

Currently, the example below that is without the use of array wrappers does not work. I'd like to propose that it should. In addition note the error it does produce is gargantuan and not very insightful.

``` js
var apiCheck = require('api-check')()
apiCheck.throw(apiCheck.string, 'abc')
```

```
Error: apiCheck apiCheck failed! `Argument 1` passed, `value` at `Argument 2` must be `oneOfType[function arguments, Array]`, `Argument 3 (optional)` passed

You passed:
[
  {
    "1": "abc"
  }
]

With the types of:
[
  {
    "0": "Function",
    "1": "String",
    "2": "undefined"
  }
]

The API calls for:
[
  {
    "__apiCheckData": {
      "optional": false,
      "type": "typeOrArrayOf"
    },
    "typeOrArrayOf": {
      "__apiCheckData": {
        "strict": false,
        "optional": false,
        "type": "func.withProperties"
      },
      "func.withProperties": {
        "type": {
          "__apiCheckData": {
            "optional": true,
            "type": "oneOfType"
          },
          "oneOfType": [
            "String",
            "checkerTypeType"
          ]
        },
        "displayName": "String (optional)",
        "shortType": "String (optional)",
        "notOptional": "Boolean (optional)",
        "childrenCheckers": {
          "__apiCheckData": {
            "optional": true,
            "type": "arrayOf"
          },
          "arrayOf": "String"
        }
      }
    }
  },
  {
    "__apiCheckData": {
      "optional": false,
      "type": "oneOfType"
    },
    "oneOfType": [
      "function arguments",
      "Array"
    ]
  },
  {
    "__apiCheckData": {
      "strict": true,
      "optional": true,
      "type": "shape"
    },
    "shape": {}
  }
]
    at Function.handleErrorMessage (/Users/timoxley/Projects/tests/node_modules/api-check/dist/apiCheck.js:224:14)
    at checkApiCheckApi (/Users/timoxley/Projects/tests/node_modules/api-check/dist/apiCheck.js:210:17)
    at apiCheck (/Users/timoxley/Projects/tests/node_modules/api-check/dist/apiCheck.js:171:6)
    at Function.apiCheckWrapper [as throw] (/Users/timoxley/Projects/tests/node_modules/api-check/dist/apiCheck.js:216:21)
    at repl:1:16
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
```

**Comment by kentcdodds** [comment]
I've thought about that as well. For some reason, I thought that it wouldn't be possible, but now I'm starting to wonder why I ever thought that. I'm going to be releasing a 7.0.0 with some breaking changes before too long. I'll look at implementing this as a part of that. For now, you actually don't have to specify the api as an array so this would work:

``` javascript
apiCheckInstance.throw(apiCheckInstance.string, ['abc']); // <-- passes
```

**Comment by kentcdodds** [comment]
This is obviously only if there's only one item that you're checking :-)

**Comment by kentcdodds** [comment]
This is now supported in 7.0.0. If you don't provide an array for your api, then it will expect the args to not be an array of args.

``` javascript
apiCheckInstance.throw(apiCheckInstance.string, 'abc'); // <-- passes
apiCheckInstance.throw(apiCheckInstance.string, ['abc']); // <-- fails
apiCheckInstance.throw([apiCheckInstance.string], ['abc']); // <-- passes
```
